# Generated by Django 4.0.4 on 2022-05-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_menu_text_dish_image_remove_dish_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Dish'),
        ),
    ]
