# Generated by Django 4.0.4 on 2022-05-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_dish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
    ]
